### ISSUE TITLE
Interpretation of deletions from .tsvs generated from standalone ivar vs ivar implemented in viralrecon

### ISSUE THREAD

**Issue by lyrwang** [kbessonov1984/VCFParser#1]
Hi,

Deletions are being displayed differently in the .tsv files outputted from the standalone ivar vs. ivar implemented in viral recon (example for position 11287 below). Adding both versions in the meta data file won't work because it will display them as two different deletions in the heatmap. Would it be possible to have VCFParser interrogate both options and make the correct call as to which is present?

e.g. Position 11287
.tsv generated from standalone
`MN908947.3 | 11287 | G | -NNNNNNNNN | 6206 | 3102 | 42 | 106 | 0 | 10 | 0.0135342`
.tsv generated from ivar implemented in viralrecon
`MN908947.3 | 11287 | G | -TCTGGTTTT | 3616 | 2531 | 48 | 187 | 0 | 20 | `

Thanks!
Ruth

**Comment by kbessonov1984** [comment]
I see that both outputs are showing the same deletion event. One is just more specific providing information on actual delayed nucleotides. In metadata I would prefer to have viralrecon definition with specified deleted nucleotides. Programmatically we can deal with both deletion representations by just checking for position and deletion length irrespective of actual deleted nucleotides. This would allow for both inputs being successfully analyzed. If you can send me an example file of both cases to work on Monday, it would help with testing

**Comment by kbessonov1984** [comment]
Fixed this issue in commit `6027c8e9`. Now we are filtering deletions just based on position and length irrespective of the  deleted sequence in the input tsv or vcf file. This provides a more flexible and agnostic approach.
