### ISSUE TITLE
MANIFEST.in

### ISSUE THREAD

**Issue by mattheww95** [kbessonov1984/VCFParser#2]
Manifest data path is currently vcfparser/cov-lineages-[whatever].tsv

should be vcfparser/data/cov-lineages-[whatever].tsv

**Comment by kbessonov1984** [comment]
Hi Matt,

Thank you for spotting it. Indeed when converting to a package format forgot to update that default path. Since recent commit `cdb1bf9` this issue was fixed. Alternatively you can use `-r` argument to specify custom metadata file on VOCs.

**Comment by kbessonov1984** [comment]
The path to the default metadata now is corrected
