### ISSUE TITLE
Openpyxl?

### ISSUE THREAD

**Issue by mattheww95** [kbessonov1984/VCFParser#3]
I have no idea why, I don't see it in the source code anywhere. But apparently openpyxl is needed...

Maybe add it to the install_requires=['pandas', 'matplotlib', 'numpy', 'pysam']?

I have no idea where it is hiding in the code...

**Comment by kbessonov1984** [comment]
I will add openpyxml shortly as it is the default Excel write engine in pandas. I had it installed in my dev environment and did not notice that pandas does not install it automatically. Thank you for noticing it. This shows that fresh conda or docker image are the best test environments as they replicate pure context without any prior history

**Comment by kbessonov1984** [comment]
Addressed this issue in commit `560821a`
